### ISSUE TITLE
Inquiries about the performance of compared method "ImvoxelNet" in the paper

### ISSUE THREAD

**Issue by Cindy0725** [ttaoREtw/ImGeoNet#3]
Hi, it's interesting work! I have a question about the performance of ImvoxelNet on ARKitScenes dataset stated in the paper. 
The mAP0.25 and mAP0.5 for ImvoxelNet on ARKitScenes dataset in ImGeoNet paper is very high: 
![1715839560279](https://github.com/ttaoREtw/ImGeoNet/assets/38576019/9f8e299a-8bbb-40ae-ac2a-e745c93fe71f)
But in NeRF-Det and CN-RMA paper, the mAP0.25 of ImvoxelNet on ARKitScenes is less than 30: 
![1715840200088](https://github.com/ttaoREtw/ImGeoNet/assets/38576019/895700c4-d60f-4bc1-a984-923688d4b972)
![1715840225721](https://github.com/ttaoREtw/ImGeoNet/assets/38576019/cc737845-7e2b-451d-9ba4-6f933f2c3bb6)
Could you please kindly share how you train ImvoxelNet and your model on ARKitScenes and share the code? 
Thank you very much! Looking forward to your reply.

**Comment by ttaoREtw** [comment]
The code will be released in a few days. Thanks.
